name: Retrigger Check Suites

on: 
  issue_comment:
    types: [ created ]

jobs:
  retrigger:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, 'trigger checks') }}
    steps:
    - name: Install requests
      run: pip install requests
    - name: Rerun check suite
      shell: python
      run: |
        import sys, json, requests;
        from requests.auth import HTTPBasicAuth
        pr_request = requests.get("${{ github.event.issue.pull_request.url }}")
        pr_json = pr_request.json()
        pr_sha = pr_json["head"]["sha"]
        print("PR sha: " + pr_sha)
        check_suites_url = pr_json["head"]["repo"]["commits_url"].replace("{/sha}", "/" + pr_sha) + "/check-suites"
        print("Looking up check suites from " + check_suites_url)
        suites_headers = {"Accept" : "application/vnd.github.antiope-preview+json", "authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"}
        suites_request = requests.get(check_suites_url, headers=suites_headers)
        suite_id = str(suites_request.json()["check_suites"][0]["id"])
        print("Check suite id: " + suite_id)
        rerequest_url = pr_json["head"]["repo"]["url"] + "/check-suites/" + suite_id + "/rerequest"
        print("Triggering check suite rerequest: " + rerequest_url)
        suites_rerequest = requests.post(rerequest_url, headers=suites_headers)

